id: IDA76AA46
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T00:35:00+00:00'
last_modified: '2022-06-07T16:18:56.279504+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21947
  title: པདྨ་གླིང་པའི་ཆོ་གའི་སྐོར་ལྷོ་འབྲུག་ལུགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FB0E:
      image_group_id: I1CZ3870
      title: ''
      total_pages: 546
      order: 1
      base_file: FB0E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
