id: P002934
initial_creation_type: ocr
source_metadata:
  id: bdr:W21947
  title: པདྨ་གླིང་པའི་ཆོ་གའི་སྐོར་ལྷོ་འབྲུག་ལུགས
  author: ''
  volumes:
    4872f7f2a349424ba1f1e867e62b8cbf:
      image_group_id: I1CZ3870
      title: ''
      volume_number: 1
      total_pages: 546
